name: Profile QA - full repository
on: [pull_request]

jobs:
  nictiz-r4-qa-full:
    name: Loose QA on the entire repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Zib2020 QA
        uses: Nictiz/Nictiz-R4-QA@main
        with:
          changed-only: false
          no-tx: true
