name: Profile QA - changed files
on: [pull_request]

jobs:
  nictiz-r4-qa-changed:
    name: Strict QA on changed materials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Zib2020 QA
        uses: Nictiz/Nictiz-R4-QA@main
        with:
          changed-only: true
          fail-at: "warning"
