name: Profile QA - full repository
on: pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Restore validator cache
        uses: actions/cache@v2
        with:
          path: ~/.fhir/packages
          key: fhir-cache
      - name: Copy conformance profile to the ig
        run: cp qa/ProfilingGuidelinesR4.xml resources/
      - name: Validate profiles
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.11
        with:
          version: "4.0"
          ig: resources/
          recurse: true
          profile: https://informatiestandaarden.nictiz.nl/wiki/FHIR:V1.0_FHIR_Profiling_Guidelines_R4
          source: resources/zib-*
          fail-at: warning
          ignored-issues: known-issues.yml
        continue-on-error: true
      - name: Validate examples
        uses: pieter-edelman-nictiz/hl7-fhir-validator-action@v0.11
        with:
          version: "4.0"
          ig: resources/
          recurse: true
          source: example/*
          fail-at: warning
          ignored-issues: known-issues.yml
        continue-on-error: true

      - name: Install Firely Terminal
        run: dotnet tool install -g firely.terminal
      - name: Create snapshots in JSON format
        run: |
          mkdir flattened
          cd flattened
          ln -s ../package.json
          ln -s ../fhirpkg.lock.json
          for f in $(find ../resources -name "*.xml"); do ln -s $f; done
          cd ..
          
          fhir install hl7.fhir.r4.core 4.0.1
          mkdir ../snapshots
          for sd in zib-*.xml; do
            base=$(basename $sd .xml);
            fhir push $base.xml
            fhir snapshot
            fhir save ../snapshots/$base.json --json
          done
          cd ..
      - name: Check zib compliance
        uses: pieter-edelman-nictiz/zib-compliance-fhir@action
        with:
          max-file: qa/zibs2020.max
          structuredefinitions: snapshots/*
          zib-release: 2020
          fail-at: warning
          zib-overrides: known-issues.yml

